import { COIN_TYPE, Network } from '@interest-protocol/sui-amm-sdk';
import { TOKEN_SYMBOL } from 'lib';

export const COIN_TYPE_TO_SYMBOL = {
  [Network.DEVNET]: {
    [COIN_TYPE[Network.DEVNET].BNB]: TOKEN_SYMBOL.BNB,
    [COIN_TYPE[Network.DEVNET].ETH]: TOKEN_SYMBOL.ETH,
    [COIN_TYPE[Network.DEVNET].BTC]: TOKEN_SYMBOL.BTC,
    [COIN_TYPE[Network.DEVNET].USDT]: TOKEN_SYMBOL.USDT,
    [COIN_TYPE[Network.DEVNET].USDC]: TOKEN_SYMBOL.USDC,
    [COIN_TYPE[Network.DEVNET].SUI]: TOKEN_SYMBOL.SUI,
    [COIN_TYPE[Network.DEVNET].IPX]: TOKEN_SYMBOL.IPX,
    [COIN_TYPE[Network.DEVNET].V_LP_SUI_ETH]: TOKEN_SYMBOL.V_LP_SUI_ETH,
    [COIN_TYPE[Network.DEVNET].V_LP_BTC_ETH]: TOKEN_SYMBOL.V_LP_BTC_ETH,
    [COIN_TYPE[Network.DEVNET].V_LP_BNB_ETH]: TOKEN_SYMBOL.V_LP_BNB_ETH,
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_USDT]: TOKEN_SYMBOL.V_LP_ETH_USDT,
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_USDC]: TOKEN_SYMBOL.V_LP_ETH_USDC,
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_IPX]: TOKEN_SYMBOL.V_LP_ETH_IPX,
  },
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BNB]: TOKEN_SYMBOL.BNB,
    [COIN_TYPE[Network.TESTNET].ETH]: TOKEN_SYMBOL.ETH,
    [COIN_TYPE[Network.TESTNET].BTC]: TOKEN_SYMBOL.BTC,
    [COIN_TYPE[Network.TESTNET].USDT]: TOKEN_SYMBOL.USDT,
    [COIN_TYPE[Network.TESTNET].USDC]: TOKEN_SYMBOL.USDC,
    [COIN_TYPE[Network.TESTNET].SUI]: TOKEN_SYMBOL.SUI,
    [COIN_TYPE[Network.TESTNET].IPX]: TOKEN_SYMBOL.IPX,
    [COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH]: TOKEN_SYMBOL.V_LP_SUI_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH]: TOKEN_SYMBOL.V_LP_BTC_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH]: TOKEN_SYMBOL.V_LP_BNB_ETH,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT]: TOKEN_SYMBOL.V_LP_ETH_USDT,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC]: TOKEN_SYMBOL.V_LP_ETH_USDC,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_IPX]: TOKEN_SYMBOL.V_LP_ETH_IPX,
    [COIN_TYPE[Network.TESTNET].SUID]: TOKEN_SYMBOL.SUID,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: TOKEN_SYMBOL.SUI,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: TOKEN_SYMBOL.ETH,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: TOKEN_SYMBOL.USDC,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: TOKEN_SYMBOL.USDT,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]:
      TOKEN_SYMBOL.WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]:
      TOKEN_SYMBOL.WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]:
      TOKEN_SYMBOL.WORMHOLE_WFTM,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]:
      TOKEN_SYMBOL.WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]: TOKEN_SYMBOL.WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]:
      TOKEN_SYMBOL.WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: TOKEN_SYMBOL.WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: TOKEN_SYMBOL.WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: TOKEN_SYMBOL.WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: TOKEN_SYMBOL.WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: TOKEN_SYMBOL.WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]:
      TOKEN_SYMBOL.WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: TOKEN_SYMBOL.WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT]:
      TOKEN_SYMBOL.S_LP_WORMHOLE_USDC_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WBNB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WMATIC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_CELO,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_WAVAX,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ADA,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_BTCB,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDT,
    [COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC]:
      TOKEN_SYMBOL.S_LP_WORMHOLE_USDT_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC]:
      TOKEN_SYMBOL.S_LP_WORMHOLE_USDC_WORMHOLE_USDC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_FLOKI,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_DOGE,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_ETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL]:
      TOKEN_SYMBOL.V_LP_SUI_WORMHOLE_SOL,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]: TOKEN_SYMBOL.ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]: TOKEN_SYMBOL.ETH_CELER_USDC,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]: TOKEN_SYMBOL.ETH_CELER_WETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WBTC]:
      TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_WBTC,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_WETH]:
      TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_WETH,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_CELER_USDC]:
      TOKEN_SYMBOL.V_LP_SUI_ETH_CELER_USDC,
  },
};

export const COIN_DECIMALS = {
  [Network.DEVNET]: {
    [COIN_TYPE[Network.DEVNET].BTC]: 9,
    [COIN_TYPE[Network.DEVNET].ETH]: 9,
    [COIN_TYPE[Network.DEVNET].BNB]: 9,
    [COIN_TYPE[Network.DEVNET].USDT]: 9,
    [COIN_TYPE[Network.DEVNET].USDC]: 9,
    [COIN_TYPE[Network.DEVNET].SUI]: 9,
    [COIN_TYPE[Network.DEVNET].IPX]: 9,
    [COIN_TYPE[Network.DEVNET].V_LP_SUI_ETH]: 0,
    [COIN_TYPE[Network.DEVNET].V_LP_BTC_ETH]: 0,
    [COIN_TYPE[Network.DEVNET].V_LP_BNB_ETH]: 0,
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_USDT]: 0,
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_USDC]: 0,
    [COIN_TYPE[Network.DEVNET].V_LP_ETH_IPX]: 0,
    [COIN_TYPE[Network.DEVNET].S_LP_USDC_USDT]: 0,
  },
  [Network.TESTNET]: {
    [COIN_TYPE[Network.TESTNET].BTC]: 9,
    [COIN_TYPE[Network.TESTNET].ETH]: 9,
    [COIN_TYPE[Network.TESTNET].BNB]: 9,
    [COIN_TYPE[Network.TESTNET].USDT]: 9,
    [COIN_TYPE[Network.TESTNET].USDC]: 9,
    [COIN_TYPE[Network.TESTNET].SUI]: 9,
    [COIN_TYPE[Network.TESTNET].IPX]: 9,
    [COIN_TYPE[Network.TESTNET].V_LP_SUI_ETH]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_BTC_ETH]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_BNB_ETH]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDT]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_USDC]: 0,
    [COIN_TYPE[Network.TESTNET].V_LP_ETH_IPX]: 0,
    [COIN_TYPE[Network.TESTNET].S_LP_USDC_USDT]: 0,
    [COIN_TYPE[Network.TESTNET].SUID]: 9,
  },
  [Network.MAINNET]: {
    [COIN_TYPE[Network.MAINNET].SUI]: 9,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_ETH]: 8,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDC]: 6,
    [COIN_TYPE[Network.MAINNET].ETH_WORMHOLE_USDT]: 6,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WBNB]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_SOL]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WAVAX]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WFTM]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_CELO]: 8,
    [COIN_TYPE[Network.MAINNET].NATIVE_WORMHOLE_WMATIC]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ADA]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_BTCB]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDC]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_USDT]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_ETH]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_FLOKI]: 8,
    [COIN_TYPE[Network.MAINNET].BSC_WORMHOLE_DOGE]: 8,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_ETH_WORMHOLE_USDT]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_ETH]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_ETH_WORMHOLE_USDT]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WBNB]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WMATIC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_CELO]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_WAVAX]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ADA]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_BTCB]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDT]: 0,
    [COIN_TYPE[Network.MAINNET].S_LP_BSC_WORMHOLE_USDT_BSC_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].S_LP_ETH_WORMHOLE_USDC_BSC_WORMHOLE_USDC]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_FLOKI]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_DOGE]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_BSC_WORMHOLE_ETH]: 0,
    [COIN_TYPE[Network.MAINNET].V_LP_SUI_NATIVE_WORMHOLE_SOL]: 0,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WETH]: 9,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_WBTC]: 8,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDC]: 6,
    [COIN_TYPE[Network.MAINNET].ETH_CELER_USDT]: 6,
  },
};
